# !!! This Docker Compose file is intended for local development only !!!
# Deployment for production and other environments is managed via Kubernetes (see /k8s directory).
services:
  postgres:
    image: postgres:17-alpine
    container_name: ticket-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ticket-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: ticket-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbgate:
    image: dbgate/dbgate:latest
    container_name: ticket-dbgate
    ports:
      - "3000:3000"
    volumes:
      - dbgate_data:/root/.dbgate
    environment:
      - CONNECTIONS=con1,con2
      - LABEL_con1=Postgres
      - SERVER_con1=postgres
      - USER_con1=${DB_USER}
      - PASSWORD_con1=${DB_PASSWORD}
      - PORT_con1=5432
      - ENGINE_con1=postgres@dbgate-plugin-postgres
      - LABEL_con2=Redis
      - SERVER_con2=redis
      - PASSWORD_con2=${REDIS_PASSWORD}
      - PORT_con2=6379
      - ENGINE_con2=redis@dbgate-plugin-redis
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  dbgate_data:
