# #############################################################################
# Use the Taskfile command to generate a new configmap.yaml from your .env:
# task k8s:configmap
# #############################################################################
apiVersion: v1
data:
  DB_HOST: postgres
  DB_NAME: ticketdb
  DB_PORT: "5432"
  DB_USER: ticketuser
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: rabbituser
  REDIS_HOST: redis
  REDIS_PORT: "6379"
kind: ConfigMap
metadata:
  name: ticket-system-config
  namespace: ticket-system
