apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticket-system-ingress
  namespace: ticket-system
  annotations:
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/api"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Ticket API Route
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ticket-api
                port:
                  number: 8080
          # Grafana routing
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
