{
 "title": "Ticket System",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Orders for timeslot",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ticketdb",
     "rawSql": "SELECT\r\n  COUNT(id) AS value\r\nFROM orders\r\nWHERE $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Orders over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "ticketdb",
     "rawSql": "SELECT\r\n  $__timeGroup(created_at, $__interval) AS \"time\",\r\n  COUNT(id) FILTER (WHERE status = 'COMPLETED') AS \"COMPLETED\",\r\n  COUNT(id) FILTER (WHERE status = 'PENDING') AS \"PENDING\",\r\n  COUNT(id) FILTER (WHERE status = 'FAILED') AS \"FAILED\"\r\nFROM orders\r\nWHERE $__timeFilter(created_at)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ticket Availability",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ticketdb",
     "rawSql": "SELECT\r\n  COUNT(id) FILTER (WHERE status = 'SOLD') AS \"SOLD\",\r\n  COUNT(id) FILTER (WHERE status = 'AVAILABLE') AS \"AVAILABLE\"\r\nFROM tickets"
    }
   ]
  },
  {
   "title": "Pods CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"ticket-system\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods RAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"ticket-system\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket API - Traffic (Requests per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"ticket-system\", uri!~\"/actuator.*|/swagger.*|/v3/api-docs.*\"}[5m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket API - API Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n  sum(rate(http_server_requests_seconds_bucket{namespace=\"ticket-system\", uri!~\"/actuator.*|/swagger.*|/v3/api-docs.*\"}[5m])) \r\n  by (le, uri)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}